/* NOTE: Do not edit this file, it is generated by a script:
   Export.py --api gl 4.2 --api wgl 4.0 --api glx 4.0 --api cgl 1.4 --api egl 1.0 --outdir src/regal
*/

/*
  Copyright (c) 2011 NVIDIA Corporation
  Copyright (c) 2011-2012 Cass Everitt
  Copyright (c) 2012 Scott Nations
  Copyright (c) 2012 Mathias Schott
  Copyright (c) 2012 Nigel Stewart
  All rights reserved.

  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

    Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

    Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
  OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "pch.h" /* For MS precompiled header support */

#include "RegalUtil.h"

REGAL_GLOBAL_BEGIN

#include "RegalContext.h"
#include "RegalContextInfo.h"
#include "RegalObj.h"
#include "RegalMarker.h"
#include "RegalBin.h"
#include "RegalDsa.h"
#include "RegalIff.h"
#include "RegalVao.h"

REGAL_GLOBAL_END

REGAL_NAMESPACE_BEGIN

using namespace Logging;

void RegalContext::Init()
{
   ITrace("RegalContext::Init()");
   dsp.Init();
   err.Init();
   info = new ContextInfo();
   RegalAssert(this);
   RegalAssert(info);
   info->init(*this);
       // emu
   emuLevel = 7;
   vao = NULL;
   iff = NULL;
   dsa = NULL;
   bin = NULL;
   marker = NULL;
   obj = NULL;
   if( !RegalGetEnv( "REGAL_NO_EMULATION" ) ) {
      vao = new RegalVao;
      vao->emuLevel = 1;
      vao->Init( this );
      iff = new RegalIff;
      iff->emuLevel = 2;
      iff->Init( this );
      dsa = new RegalDsa;
      dsa->emuLevel = 3;
      dsa->Init( this );
      bin = new RegalBin;
      bin->emuLevel = 4;
      bin->Init( this );
      marker = new RegalMarker;
      marker->emuLevel = 5;
      marker->Init( this );
      obj = new RegalObj;
      obj->emuLevel = 7;
      obj->Init( this );
   }

   sysCtx = 0;
   thr = 0;
}

void RegalContext::Cleanup()
{
   ITrace("RegalContext::Cleanup()");
   delete info;
   // emu
   delete obj;
   delete marker;
   delete bin;
   delete dsa;
   delete iff;
   delete vao;

}

REGAL_NAMESPACE_END
