/* NOTE: Do not edit this file, it is generated by a script:
   Export.py --api gl 4.2 --api wgl 4.0 --api glx 4.0 --api cgl 1.4 --api egl 1.0 --outdir src/regal
*/

/*
  Copyright (c) 2011 NVIDIA Corporation
  Copyright (c) 2011-2012 Cass Everitt
  Copyright (c) 2012 Scott Nations
  Copyright (c) 2012 Mathias Schott
  Copyright (c) 2012 Nigel Stewart
  All rights reserved.

  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

    Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

    Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
  OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "pch.h" /* For MS precompiled header support */

#include "RegalUtil.h"

REGAL_GLOBAL_BEGIN

#include <GL/Regal.h>

#include <string>
#include <set>
using namespace std;

#include <boost/print/string_list.hpp>
using namespace boost::print;

#include "RegalContext.h"
#include "RegalContextInfo.h"
#include "RegalIff.h"             // For REGAL_MAX_VERTEX_ATTRIBS

REGAL_GLOBAL_END

REGAL_NAMESPACE_BEGIN

using namespace Logging;

ContextInfo::ContextInfo()
:
  compat(false),
  core(false),
  gles(false),
  gl_version_major(-1),
  gl_version_minor(-1),
  gl_version_1_0(false),
  gl_version_1_1(false),
  gl_version_1_2(false),
  gl_version_1_3(false),
  gl_version_1_4(false),
  gl_version_1_5(false),
  gl_version_2_0(false),
  gl_version_2_1(false),
  gl_version_3_0(false),
  gl_version_3_1(false),
  gl_version_3_2(false),
  gl_version_3_3(false),
  gl_version_4_0(false),
  gl_version_4_1(false),
  gl_version_4_2(false),
  gles_version_major(-1),
  gles_version_minor(-1),
  glsl_version_major(-1),
  glsl_version_minor(-1),
  glx_version_major(-1),
  glx_version_minor(-1),
  glx_version_1_0(false),
  glx_version_1_1(false),
  glx_version_1_2(false),
  glx_version_1_3(false),
  glx_version_1_4(false),
  gl_3dfx_tbuffer(false),
  gl_amd_debug_output(false),
  gl_amd_draw_buffers_blend(false),
  gl_amd_multi_draw_indirect(false),
  gl_amd_name_gen_delete(false),
  gl_amd_performance_monitor(false),
  gl_amd_sample_positions(false),
  gl_amd_stencil_operation_extended(false),
  gl_amd_vertex_shader_tessellator(false),
  gl_apple_element_array(false),
  gl_apple_fence(false),
  gl_apple_flush_buffer_range(false),
  gl_apple_flush_render(false),
  gl_apple_object_purgeable(false),
  gl_apple_texture_range(false),
  gl_apple_vertex_array_object(false),
  gl_apple_vertex_array_range(false),
  gl_apple_vertex_program_evaluators(false),
  gl_arb_es2_compatibility(false),
  gl_arb_base_instance(false),
  gl_arb_blend_func_extended(false),
  gl_arb_cl_event(false),
  gl_arb_color_buffer_float(false),
  gl_arb_copy_buffer(false),
  gl_arb_debug_output(false),
  gl_arb_draw_buffers(false),
  gl_arb_draw_buffers_blend(false),
  gl_arb_draw_elements_base_vertex(false),
  gl_arb_draw_indirect(false),
  gl_arb_draw_instanced(false),
  gl_arb_framebuffer_object(false),
  gl_arb_geometry_shader4(false),
  gl_arb_get_program_binary(false),
  gl_arb_gpu_shader_fp64(false),
  gl_arb_half_float_pixel(false),
  gl_arb_imaging(false),
  gl_arb_instanced_arrays(false),
  gl_arb_internalformat_query(false),
  gl_arb_map_buffer_range(false),
  gl_arb_matrix_palette(false),
  gl_arb_multisample(false),
  gl_arb_multitexture(false),
  gl_arb_occlusion_query(false),
  gl_arb_point_parameters(false),
  gl_arb_provoking_vertex(false),
  gl_arb_robustness(false),
  gl_arb_sample_shading(false),
  gl_arb_sampler_objects(false),
  gl_arb_separate_shader_objects(false),
  gl_arb_shader_objects(false),
  gl_arb_shader_subroutine(false),
  gl_arb_shading_language_include(false),
  gl_arb_sync(false),
  gl_arb_tessellation_shader(false),
  gl_arb_texture_buffer_object(false),
  gl_arb_texture_compression(false),
  gl_arb_texture_multisample(false),
  gl_arb_texture_storage(false),
  gl_arb_timer_query(false),
  gl_arb_transform_feedback2(false),
  gl_arb_transform_feedback3(false),
  gl_arb_transform_feedback_instanced(false),
  gl_arb_transpose_matrix(false),
  gl_arb_uniform_buffer_object(false),
  gl_arb_vertex_array_object(false),
  gl_arb_vertex_attrib_64bit(false),
  gl_arb_vertex_blend(false),
  gl_arb_vertex_buffer_object(false),
  gl_arb_vertex_program(false),
  gl_arb_vertex_shader(false),
  gl_arb_vertex_type_2_10_10_10_rev(false),
  gl_arb_viewport_array(false),
  gl_arb_window_pos(false),
  gl_ati_draw_buffers(false),
  gl_ati_element_array(false),
  gl_ati_envmap_bumpmap(false),
  gl_ati_fragment_shader(false),
  gl_ati_map_object_buffer(false),
  gl_ati_pn_triangles(false),
  gl_ati_separate_stencil(false),
  gl_ati_vertex_array_object(false),
  gl_ati_vertex_attrib_array_object(false),
  gl_ati_vertex_streams(false),
  gl_ext_bindable_uniform(false),
  gl_ext_blend_color(false),
  gl_ext_blend_equation_separate(false),
  gl_ext_blend_func_separate(false),
  gl_ext_blend_minmax(false),
  gl_ext_color_subtable(false),
  gl_ext_compiled_vertex_array(false),
  gl_ext_convolution(false),
  gl_ext_coordinate_frame(false),
  gl_ext_copy_texture(false),
  gl_ext_cull_vertex(false),
  gl_ext_debug_marker(false),
  gl_ext_depth_bounds_test(false),
  gl_ext_direct_state_access(false),
  gl_ext_draw_buffers2(false),
  gl_ext_draw_instanced(false),
  gl_ext_draw_range_elements(false),
  gl_ext_fog_coord(false),
  gl_ext_fragment_lighting(false),
  gl_ext_framebuffer_blit(false),
  gl_ext_framebuffer_multisample(false),
  gl_ext_framebuffer_object(false),
  gl_ext_geometry_shader4(false),
  gl_ext_gpu_program_parameters(false),
  gl_ext_gpu_shader4(false),
  gl_ext_histogram(false),
  gl_ext_index_func(false),
  gl_ext_index_material(false),
  gl_ext_light_texture(false),
  gl_ext_multi_draw_arrays(false),
  gl_ext_multisample(false),
  gl_ext_paletted_texture(false),
  gl_ext_pixel_transform(false),
  gl_ext_point_parameters(false),
  gl_ext_polygon_offset(false),
  gl_ext_provoking_vertex(false),
  gl_ext_scene_marker(false),
  gl_ext_secondary_color(false),
  gl_ext_separate_shader_objects(false),
  gl_ext_shader_image_load_store(false),
  gl_ext_stencil_clear_tag(false),
  gl_ext_stencil_two_side(false),
  gl_ext_subtexture(false),
  gl_ext_texture3d(false),
  gl_ext_texture_array(false),
  gl_ext_texture_buffer_object(false),
  gl_ext_texture_integer(false),
  gl_ext_texture_object(false),
  gl_ext_texture_perturb_normal(false),
  gl_ext_timer_query(false),
  gl_ext_transform_feedback(false),
  gl_ext_vertex_array(false),
  gl_ext_vertex_attrib_64bit(false),
  gl_ext_vertex_shader(false),
  gl_ext_vertex_weighting(false),
  gl_ext_x11_sync_object(false),
  gl_gremedy_frame_terminator(false),
  gl_gremedy_string_marker(false),
  gl_hp_image_transform(false),
  gl_ibm_multimode_draw_arrays(false),
  gl_ibm_vertex_array_lists(false),
  gl_ingr_blend_func_separate(false),
  gl_intel_parallel_arrays(false),
  gl_intel_texture_scissor(false),
  gl_ktx_buffer_region(false),
  gl_mesa_resize_buffers(false),
  gl_mesa_window_pos(false),
  gl_nv_bindless_texture(false),
  gl_nv_conditional_render(false),
  gl_nv_copy_image(false),
  gl_nv_depth_buffer_float(false),
  gl_nv_evaluators(false),
  gl_nv_explicit_multisample(false),
  gl_nv_fence(false),
  gl_nv_fragment_program(false),
  gl_nv_framebuffer_multisample_coverage(false),
  gl_nv_geometry_program4(false),
  gl_nv_gpu_program4(false),
  gl_nv_gpu_shader5(false),
  gl_nv_half_float(false),
  gl_nv_occlusion_query(false),
  gl_nv_parameter_buffer_object(false),
  gl_nv_path_rendering(false),
  gl_nv_pixel_data_range(false),
  gl_nv_point_sprite(false),
  gl_nv_present_video(false),
  gl_nv_primitive_restart(false),
  gl_nv_register_combiners(false),
  gl_nv_register_combiners2(false),
  gl_nv_shader_buffer_load(false),
  gl_nv_texture_barrier(false),
  gl_nv_texture_multisample(false),
  gl_nv_transform_feedback(false),
  gl_nv_transform_feedback2(false),
  gl_nv_vdpau_interop(false),
  gl_nv_vertex_array_range(false),
  gl_nv_vertex_attrib_integer_64bit(false),
  gl_nv_vertex_buffer_unified_memory(false),
  gl_nv_vertex_program(false),
  gl_nv_vertex_program4(false),
  gl_nv_video_capture(false),
  gl_pgi_misc_hints(false),
  gl_regal_error_string(false),
  gl_regal_extension_query(false),
  gl_sgis_detail_texture(false),
  gl_sgis_fog_function(false),
  gl_sgis_multisample(false),
  gl_sgis_pixel_texture(false),
  gl_sgis_point_parameters(false),
  gl_sgis_sharpen_texture(false),
  gl_sgis_texture4d(false),
  gl_sgis_texture_color_mask(false),
  gl_sgis_texture_filter4(false),
  gl_sgix_async(false),
  gl_sgix_flush_raster(false),
  gl_sgix_fog_texture(false),
  gl_sgix_fragment_lighting(false),
  gl_sgix_framezoom(false),
  gl_sgix_igloo_interface(false),
  gl_sgix_instruments(false),
  gl_sgix_list_priority(false),
  gl_sgix_pixel_texture(false),
  gl_sgix_polynomial_ffd(false),
  gl_sgix_reference_plane(false),
  gl_sgix_sprite(false),
  gl_sgix_tag_sample_buffer(false),
  gl_sgi_color_table(false),
  gl_sunx_constant_data(false),
  gl_sun_global_alpha(false),
  gl_sun_mesh_array(false),
  gl_sun_read_video_pixels(false),
  gl_sun_triangle_list(false),
  gl_sun_vertex(false),
  gl_win_swap_hint(false),
#ifdef REGAL_SYS_WGL
  wgl_3dl_stereo_control(false),
  wgl_amd_gpu_association(false),
  wgl_arb_buffer_region(false),
  wgl_arb_create_context(false),
  wgl_arb_extensions_string(false),
  wgl_arb_make_current_read(false),
  wgl_arb_pbuffer(false),
  wgl_arb_pixel_format(false),
  wgl_arb_render_texture(false),
  wgl_ext_display_color_table(false),
  wgl_ext_extensions_string(false),
  wgl_ext_make_current_read(false),
  wgl_ext_pbuffer(false),
  wgl_ext_pixel_format(false),
  wgl_ext_swap_control(false),
  wgl_gdi(false),
  wgl_i3d_digital_video_control(false),
  wgl_i3d_gamma(false),
  wgl_i3d_genlock(false),
  wgl_i3d_image_buffer(false),
  wgl_i3d_swap_frame_lock(false),
  wgl_i3d_swap_frame_usage(false),
  wgl_nv_copy_image(false),
  wgl_nv_gpu_affinity(false),
  wgl_nv_present_video(false),
  wgl_nv_swap_group(false),
  wgl_nv_vertex_array_range(false),
  wgl_nv_video_capture(false),
  wgl_nv_video_output(false),
  wgl_oml_sync_control(false),
#endif
#ifdef REGAL_SYS_GLX
  glx_arb_create_context(false),
  glx_arb_get_proc_address(false),
  glx_ati_render_texture(false),
  glx_ext_import_context(false),
  glx_ext_swap_control(false),
  glx_ext_texture_from_pixmap(false),
  glx_mesa_agp_offset(false),
  glx_mesa_copy_sub_buffer(false),
  glx_mesa_pixmap_colormap(false),
  glx_mesa_release_buffers(false),
  glx_mesa_set_3dfx_mode(false),
  glx_nv_copy_image(false),
  glx_nv_present_video(false),
  glx_nv_swap_group(false),
  glx_nv_vertex_array_range(false),
  glx_nv_video_output(false),
  glx_oml_sync_control(false),
  glx_sgix_fbconfig(false),
  glx_sgix_pbuffer(false),
  glx_sgix_swap_barrier(false),
  glx_sgix_swap_group(false),
  glx_sgix_video_resize(false),
  glx_sgi_cushion(false),
  glx_sgi_make_current_read(false),
  glx_sgi_swap_control(false),
  glx_sgi_video_sync(false),
  glx_sun_get_transparent_index(false),
  glx_sun_video_resize(false),
#endif

  maxVertexAttribs(0)
{
   ITrace("ContextInfo::ContextInfo()");
}

ContextInfo::~ContextInfo()
{
   ITrace("ContextInfo::~ContextInfo()");
}

inline string getString(const RegalContext &context, const GLenum e)
{
  ITrace("getString ",e);
  RegalAssert(context.dsp->driverTbl.glGetString);
  const GLubyte *str = context.dsp->driverTbl.glGetString(e);
  return str ? string(reinterpret_cast<const char *>(str)) : string();
}

void
ContextInfo::init(const RegalContext &context)
{
  // OpenGL Version.

  vendor     = getString(context, GL_VENDOR);
  renderer   = getString(context, GL_RENDERER);
  version    = getString(context, GL_VERSION);

  Info("OpenGL vendor    : ",vendor);
  Info("OpenGL renderer  : ",renderer);
  Info("OpenGL version   : ",version);

  gl_version_major = 0;
  gl_version_minor = 0;

  gles_version_major = 0;
  gles_version_minor = 0;

  // Detect GL context version

  gles = starts_with(version,"OpenGL ES ");
  if (gles)
    sscanf(version.c_str(), "OpenGL ES %d.%d", &gles_version_major, &gles_version_minor);
  else
    sscanf(version.c_str(), "%d.%d", &gl_version_major, &gl_version_minor);

  // Detect core context

  if (!gles && gl_version_major>=3)
  {
    GLint flags = 0;
    RegalAssert(context.dsp->driverTbl.glGetIntegerv);
    context.dsp->driverTbl.glGetIntegerv(GL_CONTEXT_PROFILE_MASK, &flags);
    core = flags & GL_CONTEXT_CORE_PROFILE_BIT ? GL_TRUE : GL_FALSE;
  }

  compat = !core && !gles;

  // Detect extensions

  string_list<string> extList;

  if (core)
  {
    RegalAssert(context.dsp->driverTbl.glGetStringi);
    RegalAssert(context.dsp->driverTbl.glGetIntegerv);

    GLint n = 0;
    context.dsp->driverTbl.glGetIntegerv(GL_NUM_EXTENSIONS, &n);

    for (GLint i=0; i<n; ++i)
      extList.push_back(reinterpret_cast<const char *>(context.dsp->driverTbl.glGetStringi(GL_EXTENSIONS,i)));
    extensions = extList.join(" ");
  }
  else
  {
    extensions = getString(context, GL_EXTENSIONS);
    extList.split(extensions,' ');
  }

  Info("OpenGL extensions: ",extensions);

  // Vendor, rendering, version, extensions reported by Regal to application

  set<string> e;
  e.insert(extList.begin(),extList.end());

  // TODO - filter out extensions Regal doesn't support?

#ifdef REGAL_GL_VENDOR
  regalVendor = REGAL_EQUOTE(REGAL_GL_VENDOR);
#else
  regalVendor = vendor;
#endif

#ifdef REGAL_GL_RENDERER
  regalRenderer = REGAL_EQUOTE(REGAL_GL_RENDERER);
#else
  regalRenderer = renderer;
#endif

#ifdef REGAL_GL_VERSION
  regalVersion = REGAL_EQUOTE(REGAL_GL_VERSION);
#else
  regalVersion = version;
#endif

#ifdef REGAL_GL_EXTENSIONS
  regalExtensions = REGAL_EQUOTE(REGAL_GL_EXTENSIONS);
#else
  static const char *ourExtensions[3] = {
    "GL_REGAL_error_string",
    "GL_REGAL_extension_query",
    "GL_REGAL_log"
  };
  e.insert(&ourExtensions[0],&ourExtensions[3]);
  regalExtensions = ::boost::print::detail::join(e,string(" "));
#endif

#ifndef REGAL_NO_GETENV
  {
    const char *vendorEnv = GetEnv("REGAL_GL_VENDOR");
    if (vendorEnv) regalVendor = vendorEnv;

    const char *rendererEnv = GetEnv("REGAL_GL_RENDERER");
    if (rendererEnv) regalRenderer = rendererEnv;

    const char *versionEnv = GetEnv("REGAL_GL_VERSION");
    if (versionEnv) regalVersion = versionEnv;

    const char *extensionsEnv = GetEnv("REGAL_GL_EXTENSIONS");
    if (extensionsEnv) regalExtensions = extensionsEnv;
  }
#endif

  Info("Regal vendor     : ",regalVendor);
  Info("Regal renderer   : ",regalRenderer);
  Info("Regal version    : ",regalVersion);
  Info("Regal extensions : ",regalExtensions);

  if (!gles)
  {
    gl_version_4_2 = gl_version_major > 4 || (gl_version_major == 4 && gl_version_minor >= 2);
    gl_version_4_1 = gl_version_4_2 || (gl_version_major == 4 && gl_version_minor == 1);
    gl_version_4_0 = gl_version_4_1 || gl_version_major == 4;
    gl_version_3_3 = gl_version_4_0 || (gl_version_major == 3 && gl_version_minor == 3);
    gl_version_3_2 = gl_version_3_3 || (gl_version_major == 3 && gl_version_minor == 2);
    gl_version_3_1 = gl_version_3_2 || (gl_version_major == 3 && gl_version_minor == 1);
    gl_version_3_0 = gl_version_3_1 || gl_version_major == 3;
    gl_version_2_1 = gl_version_3_0 || (gl_version_major == 2 && gl_version_minor == 1);
    gl_version_2_0 = gl_version_2_1 || gl_version_major == 2;
    gl_version_1_5 = gl_version_2_0 || (gl_version_major == 1 && gl_version_minor == 5);
    gl_version_1_4 = gl_version_1_5 || (gl_version_major == 1 && gl_version_minor == 4);
    gl_version_1_3 = gl_version_1_4 || (gl_version_major == 1 && gl_version_minor == 3);
    gl_version_1_2 = gl_version_1_3 || (gl_version_major == 1 && gl_version_minor == 2);
    gl_version_1_1 = gl_version_1_2 || (gl_version_major == 1 && gl_version_minor == 1);
    gl_version_1_0 = gl_version_1_1 || gl_version_major == 1;
  }

  glx_version_1_4 = glx_version_major > 1 || (glx_version_major == 1 && glx_version_minor >= 4);
  glx_version_1_3 = glx_version_1_4 || (glx_version_major == 1 && glx_version_minor == 3);
  glx_version_1_2 = glx_version_1_3 || (glx_version_major == 1 && glx_version_minor == 2);
  glx_version_1_1 = glx_version_1_2 || (glx_version_major == 1 && glx_version_minor == 1);
  glx_version_1_0 = glx_version_1_1 || glx_version_major == 1;

  gl_3dfx_tbuffer = e.find("GL_3DFX_tbuffer")!=e.end();
  gl_amd_debug_output = e.find("GL_AMD_debug_output")!=e.end();
  gl_amd_draw_buffers_blend = e.find("GL_AMD_draw_buffers_blend")!=e.end();
  gl_amd_multi_draw_indirect = e.find("GL_AMD_multi_draw_indirect")!=e.end();
  gl_amd_name_gen_delete = e.find("GL_AMD_name_gen_delete")!=e.end();
  gl_amd_performance_monitor = e.find("GL_AMD_performance_monitor")!=e.end();
  gl_amd_sample_positions = e.find("GL_AMD_sample_positions")!=e.end();
  gl_amd_stencil_operation_extended = e.find("GL_AMD_stencil_operation_extended")!=e.end();
  gl_amd_vertex_shader_tessellator = e.find("GL_AMD_vertex_shader_tessellator")!=e.end();
  gl_apple_element_array = e.find("GL_APPLE_element_array")!=e.end();
  gl_apple_fence = e.find("GL_APPLE_fence")!=e.end();
  gl_apple_flush_buffer_range = e.find("GL_APPLE_flush_buffer_range")!=e.end();
  gl_apple_flush_render = e.find("GL_APPLE_flush_render")!=e.end();
  gl_apple_object_purgeable = e.find("GL_APPLE_object_purgeable")!=e.end();
  gl_apple_texture_range = e.find("GL_APPLE_texture_range")!=e.end();
  gl_apple_vertex_array_object = e.find("GL_APPLE_vertex_array_object")!=e.end();
  gl_apple_vertex_array_range = e.find("GL_APPLE_vertex_array_range")!=e.end();
  gl_apple_vertex_program_evaluators = e.find("GL_APPLE_vertex_program_evaluators")!=e.end();
  gl_arb_es2_compatibility = e.find("GL_ARB_ES2_compatibility")!=e.end();
  gl_arb_base_instance = e.find("GL_ARB_base_instance")!=e.end();
  gl_arb_blend_func_extended = e.find("GL_ARB_blend_func_extended")!=e.end();
  gl_arb_cl_event = e.find("GL_ARB_cl_event")!=e.end();
  gl_arb_color_buffer_float = e.find("GL_ARB_color_buffer_float")!=e.end();
  gl_arb_copy_buffer = e.find("GL_ARB_copy_buffer")!=e.end();
  gl_arb_debug_output = e.find("GL_ARB_debug_output")!=e.end();
  gl_arb_draw_buffers = e.find("GL_ARB_draw_buffers")!=e.end();
  gl_arb_draw_buffers_blend = e.find("GL_ARB_draw_buffers_blend")!=e.end();
  gl_arb_draw_elements_base_vertex = e.find("GL_ARB_draw_elements_base_vertex")!=e.end();
  gl_arb_draw_indirect = e.find("GL_ARB_draw_indirect")!=e.end();
  gl_arb_draw_instanced = e.find("GL_ARB_draw_instanced")!=e.end();
  gl_arb_framebuffer_object = e.find("GL_ARB_framebuffer_object")!=e.end();
  gl_arb_geometry_shader4 = e.find("GL_ARB_geometry_shader4")!=e.end();
  gl_arb_get_program_binary = e.find("GL_ARB_get_program_binary")!=e.end();
  gl_arb_gpu_shader_fp64 = e.find("GL_ARB_gpu_shader_fp64")!=e.end();
  gl_arb_half_float_pixel = e.find("GL_ARB_half_float_pixel")!=e.end();
  gl_arb_imaging = e.find("GL_ARB_imaging")!=e.end();
  gl_arb_instanced_arrays = e.find("GL_ARB_instanced_arrays")!=e.end();
  gl_arb_internalformat_query = e.find("GL_ARB_internalformat_query")!=e.end();
  gl_arb_map_buffer_range = e.find("GL_ARB_map_buffer_range")!=e.end();
  gl_arb_matrix_palette = e.find("GL_ARB_matrix_palette")!=e.end();
  gl_arb_multisample = e.find("GL_ARB_multisample")!=e.end();
  gl_arb_multitexture = e.find("GL_ARB_multitexture")!=e.end();
  gl_arb_occlusion_query = e.find("GL_ARB_occlusion_query")!=e.end();
  gl_arb_point_parameters = e.find("GL_ARB_point_parameters")!=e.end();
  gl_arb_provoking_vertex = e.find("GL_ARB_provoking_vertex")!=e.end();
  gl_arb_robustness = e.find("GL_ARB_robustness")!=e.end();
  gl_arb_sample_shading = e.find("GL_ARB_sample_shading")!=e.end();
  gl_arb_sampler_objects = e.find("GL_ARB_sampler_objects")!=e.end();
  gl_arb_separate_shader_objects = e.find("GL_ARB_separate_shader_objects")!=e.end();
  gl_arb_shader_objects = e.find("GL_ARB_shader_objects")!=e.end();
  gl_arb_shader_subroutine = e.find("GL_ARB_shader_subroutine")!=e.end();
  gl_arb_shading_language_include = e.find("GL_ARB_shading_language_include")!=e.end();
  gl_arb_sync = e.find("GL_ARB_sync")!=e.end();
  gl_arb_tessellation_shader = e.find("GL_ARB_tessellation_shader")!=e.end();
  gl_arb_texture_buffer_object = e.find("GL_ARB_texture_buffer_object")!=e.end();
  gl_arb_texture_compression = e.find("GL_ARB_texture_compression")!=e.end();
  gl_arb_texture_multisample = e.find("GL_ARB_texture_multisample")!=e.end();
  gl_arb_texture_storage = e.find("GL_ARB_texture_storage")!=e.end();
  gl_arb_timer_query = e.find("GL_ARB_timer_query")!=e.end();
  gl_arb_transform_feedback2 = e.find("GL_ARB_transform_feedback2")!=e.end();
  gl_arb_transform_feedback3 = e.find("GL_ARB_transform_feedback3")!=e.end();
  gl_arb_transform_feedback_instanced = e.find("GL_ARB_transform_feedback_instanced")!=e.end();
  gl_arb_transpose_matrix = e.find("GL_ARB_transpose_matrix")!=e.end();
  gl_arb_uniform_buffer_object = e.find("GL_ARB_uniform_buffer_object")!=e.end();
  gl_arb_vertex_array_object = e.find("GL_ARB_vertex_array_object")!=e.end();
  gl_arb_vertex_attrib_64bit = e.find("GL_ARB_vertex_attrib_64bit")!=e.end();
  gl_arb_vertex_blend = e.find("GL_ARB_vertex_blend")!=e.end();
  gl_arb_vertex_buffer_object = e.find("GL_ARB_vertex_buffer_object")!=e.end();
  gl_arb_vertex_program = e.find("GL_ARB_vertex_program")!=e.end();
  gl_arb_vertex_shader = e.find("GL_ARB_vertex_shader")!=e.end();
  gl_arb_vertex_type_2_10_10_10_rev = e.find("GL_ARB_vertex_type_2_10_10_10_rev")!=e.end();
  gl_arb_viewport_array = e.find("GL_ARB_viewport_array")!=e.end();
  gl_arb_window_pos = e.find("GL_ARB_window_pos")!=e.end();
  gl_ati_draw_buffers = e.find("GL_ATI_draw_buffers")!=e.end();
  gl_ati_element_array = e.find("GL_ATI_element_array")!=e.end();
  gl_ati_envmap_bumpmap = e.find("GL_ATI_envmap_bumpmap")!=e.end();
  gl_ati_fragment_shader = e.find("GL_ATI_fragment_shader")!=e.end();
  gl_ati_map_object_buffer = e.find("GL_ATI_map_object_buffer")!=e.end();
  gl_ati_pn_triangles = e.find("GL_ATI_pn_triangles")!=e.end();
  gl_ati_separate_stencil = e.find("GL_ATI_separate_stencil")!=e.end();
  gl_ati_vertex_array_object = e.find("GL_ATI_vertex_array_object")!=e.end();
  gl_ati_vertex_attrib_array_object = e.find("GL_ATI_vertex_attrib_array_object")!=e.end();
  gl_ati_vertex_streams = e.find("GL_ATI_vertex_streams")!=e.end();
  gl_ext_bindable_uniform = e.find("GL_EXT_bindable_uniform")!=e.end();
  gl_ext_blend_color = e.find("GL_EXT_blend_color")!=e.end();
  gl_ext_blend_equation_separate = e.find("GL_EXT_blend_equation_separate")!=e.end();
  gl_ext_blend_func_separate = e.find("GL_EXT_blend_func_separate")!=e.end();
  gl_ext_blend_minmax = e.find("GL_EXT_blend_minmax")!=e.end();
  gl_ext_color_subtable = e.find("GL_EXT_color_subtable")!=e.end();
  gl_ext_compiled_vertex_array = e.find("GL_EXT_compiled_vertex_array")!=e.end();
  gl_ext_convolution = e.find("GL_EXT_convolution")!=e.end();
  gl_ext_coordinate_frame = e.find("GL_EXT_coordinate_frame")!=e.end();
  gl_ext_copy_texture = e.find("GL_EXT_copy_texture")!=e.end();
  gl_ext_cull_vertex = e.find("GL_EXT_cull_vertex")!=e.end();
  gl_ext_debug_marker = e.find("GL_EXT_debug_marker")!=e.end();
  gl_ext_depth_bounds_test = e.find("GL_EXT_depth_bounds_test")!=e.end();
  gl_ext_direct_state_access = e.find("GL_EXT_direct_state_access")!=e.end();
  gl_ext_draw_buffers2 = e.find("GL_EXT_draw_buffers2")!=e.end();
  gl_ext_draw_instanced = e.find("GL_EXT_draw_instanced")!=e.end();
  gl_ext_draw_range_elements = e.find("GL_EXT_draw_range_elements")!=e.end();
  gl_ext_fog_coord = e.find("GL_EXT_fog_coord")!=e.end();
  gl_ext_fragment_lighting = e.find("GL_EXT_fragment_lighting")!=e.end();
  gl_ext_framebuffer_blit = e.find("GL_EXT_framebuffer_blit")!=e.end();
  gl_ext_framebuffer_multisample = e.find("GL_EXT_framebuffer_multisample")!=e.end();
  gl_ext_framebuffer_object = e.find("GL_EXT_framebuffer_object")!=e.end();
  gl_ext_geometry_shader4 = e.find("GL_EXT_geometry_shader4")!=e.end();
  gl_ext_gpu_program_parameters = e.find("GL_EXT_gpu_program_parameters")!=e.end();
  gl_ext_gpu_shader4 = e.find("GL_EXT_gpu_shader4")!=e.end();
  gl_ext_histogram = e.find("GL_EXT_histogram")!=e.end();
  gl_ext_index_func = e.find("GL_EXT_index_func")!=e.end();
  gl_ext_index_material = e.find("GL_EXT_index_material")!=e.end();
  gl_ext_light_texture = e.find("GL_EXT_light_texture")!=e.end();
  gl_ext_multi_draw_arrays = e.find("GL_EXT_multi_draw_arrays")!=e.end();
  gl_ext_multisample = e.find("GL_EXT_multisample")!=e.end();
  gl_ext_paletted_texture = e.find("GL_EXT_paletted_texture")!=e.end();
  gl_ext_pixel_transform = e.find("GL_EXT_pixel_transform")!=e.end();
  gl_ext_point_parameters = e.find("GL_EXT_point_parameters")!=e.end();
  gl_ext_polygon_offset = e.find("GL_EXT_polygon_offset")!=e.end();
  gl_ext_provoking_vertex = e.find("GL_EXT_provoking_vertex")!=e.end();
  gl_ext_scene_marker = e.find("GL_EXT_scene_marker")!=e.end();
  gl_ext_secondary_color = e.find("GL_EXT_secondary_color")!=e.end();
  gl_ext_separate_shader_objects = e.find("GL_EXT_separate_shader_objects")!=e.end();
  gl_ext_shader_image_load_store = e.find("GL_EXT_shader_image_load_store")!=e.end();
  gl_ext_stencil_clear_tag = e.find("GL_EXT_stencil_clear_tag")!=e.end();
  gl_ext_stencil_two_side = e.find("GL_EXT_stencil_two_side")!=e.end();
  gl_ext_subtexture = e.find("GL_EXT_subtexture")!=e.end();
  gl_ext_texture3d = e.find("GL_EXT_texture3D")!=e.end();
  gl_ext_texture_array = e.find("GL_EXT_texture_array")!=e.end();
  gl_ext_texture_buffer_object = e.find("GL_EXT_texture_buffer_object")!=e.end();
  gl_ext_texture_integer = e.find("GL_EXT_texture_integer")!=e.end();
  gl_ext_texture_object = e.find("GL_EXT_texture_object")!=e.end();
  gl_ext_texture_perturb_normal = e.find("GL_EXT_texture_perturb_normal")!=e.end();
  gl_ext_timer_query = e.find("GL_EXT_timer_query")!=e.end();
  gl_ext_transform_feedback = e.find("GL_EXT_transform_feedback")!=e.end();
  gl_ext_vertex_array = e.find("GL_EXT_vertex_array")!=e.end();
  gl_ext_vertex_attrib_64bit = e.find("GL_EXT_vertex_attrib_64bit")!=e.end();
  gl_ext_vertex_shader = e.find("GL_EXT_vertex_shader")!=e.end();
  gl_ext_vertex_weighting = e.find("GL_EXT_vertex_weighting")!=e.end();
  gl_ext_x11_sync_object = e.find("GL_EXT_x11_sync_object")!=e.end();
  gl_gremedy_frame_terminator = e.find("GL_GREMEDY_frame_terminator")!=e.end();
  gl_gremedy_string_marker = e.find("GL_GREMEDY_string_marker")!=e.end();
  gl_hp_image_transform = e.find("GL_HP_image_transform")!=e.end();
  gl_ibm_multimode_draw_arrays = e.find("GL_IBM_multimode_draw_arrays")!=e.end();
  gl_ibm_vertex_array_lists = e.find("GL_IBM_vertex_array_lists")!=e.end();
  gl_ingr_blend_func_separate = e.find("GL_INGR_blend_func_separate")!=e.end();
  gl_intel_parallel_arrays = e.find("GL_INTEL_parallel_arrays")!=e.end();
  gl_intel_texture_scissor = e.find("GL_INTEL_texture_scissor")!=e.end();
  gl_ktx_buffer_region = e.find("GL_KTX_buffer_region")!=e.end();
  gl_mesa_resize_buffers = e.find("GL_MESA_resize_buffers")!=e.end();
  gl_mesa_window_pos = e.find("GL_MESA_window_pos")!=e.end();
  gl_nv_bindless_texture = e.find("GL_NV_bindless_texture")!=e.end();
  gl_nv_conditional_render = e.find("GL_NV_conditional_render")!=e.end();
  gl_nv_copy_image = e.find("GL_NV_copy_image")!=e.end();
  gl_nv_depth_buffer_float = e.find("GL_NV_depth_buffer_float")!=e.end();
  gl_nv_evaluators = e.find("GL_NV_evaluators")!=e.end();
  gl_nv_explicit_multisample = e.find("GL_NV_explicit_multisample")!=e.end();
  gl_nv_fence = e.find("GL_NV_fence")!=e.end();
  gl_nv_fragment_program = e.find("GL_NV_fragment_program")!=e.end();
  gl_nv_framebuffer_multisample_coverage = e.find("GL_NV_framebuffer_multisample_coverage")!=e.end();
  gl_nv_geometry_program4 = e.find("GL_NV_geometry_program4")!=e.end();
  gl_nv_gpu_program4 = e.find("GL_NV_gpu_program4")!=e.end();
  gl_nv_gpu_shader5 = e.find("GL_NV_gpu_shader5")!=e.end();
  gl_nv_half_float = e.find("GL_NV_half_float")!=e.end();
  gl_nv_occlusion_query = e.find("GL_NV_occlusion_query")!=e.end();
  gl_nv_parameter_buffer_object = e.find("GL_NV_parameter_buffer_object")!=e.end();
  gl_nv_path_rendering = e.find("GL_NV_path_rendering")!=e.end();
  gl_nv_pixel_data_range = e.find("GL_NV_pixel_data_range")!=e.end();
  gl_nv_point_sprite = e.find("GL_NV_point_sprite")!=e.end();
  gl_nv_present_video = e.find("GL_NV_present_video")!=e.end();
  gl_nv_primitive_restart = e.find("GL_NV_primitive_restart")!=e.end();
  gl_nv_register_combiners = e.find("GL_NV_register_combiners")!=e.end();
  gl_nv_register_combiners2 = e.find("GL_NV_register_combiners2")!=e.end();
  gl_nv_shader_buffer_load = e.find("GL_NV_shader_buffer_load")!=e.end();
  gl_nv_texture_barrier = e.find("GL_NV_texture_barrier")!=e.end();
  gl_nv_texture_multisample = e.find("GL_NV_texture_multisample")!=e.end();
  gl_nv_transform_feedback = e.find("GL_NV_transform_feedback")!=e.end();
  gl_nv_transform_feedback2 = e.find("GL_NV_transform_feedback2")!=e.end();
  gl_nv_vdpau_interop = e.find("GL_NV_vdpau_interop")!=e.end();
  gl_nv_vertex_array_range = e.find("GL_NV_vertex_array_range")!=e.end();
  gl_nv_vertex_attrib_integer_64bit = e.find("GL_NV_vertex_attrib_integer_64bit")!=e.end();
  gl_nv_vertex_buffer_unified_memory = e.find("GL_NV_vertex_buffer_unified_memory")!=e.end();
  gl_nv_vertex_program = e.find("GL_NV_vertex_program")!=e.end();
  gl_nv_vertex_program4 = e.find("GL_NV_vertex_program4")!=e.end();
  gl_nv_video_capture = e.find("GL_NV_video_capture")!=e.end();
  gl_pgi_misc_hints = e.find("GL_PGI_misc_hints")!=e.end();
  gl_regal_error_string = e.find("GL_REGAL_error_string")!=e.end();
  gl_regal_extension_query = e.find("GL_REGAL_extension_query")!=e.end();
  gl_sgis_detail_texture = e.find("GL_SGIS_detail_texture")!=e.end();
  gl_sgis_fog_function = e.find("GL_SGIS_fog_function")!=e.end();
  gl_sgis_multisample = e.find("GL_SGIS_multisample")!=e.end();
  gl_sgis_pixel_texture = e.find("GL_SGIS_pixel_texture")!=e.end();
  gl_sgis_point_parameters = e.find("GL_SGIS_point_parameters")!=e.end();
  gl_sgis_sharpen_texture = e.find("GL_SGIS_sharpen_texture")!=e.end();
  gl_sgis_texture4d = e.find("GL_SGIS_texture4D")!=e.end();
  gl_sgis_texture_color_mask = e.find("GL_SGIS_texture_color_mask")!=e.end();
  gl_sgis_texture_filter4 = e.find("GL_SGIS_texture_filter4")!=e.end();
  gl_sgix_async = e.find("GL_SGIX_async")!=e.end();
  gl_sgix_flush_raster = e.find("GL_SGIX_flush_raster")!=e.end();
  gl_sgix_fog_texture = e.find("GL_SGIX_fog_texture")!=e.end();
  gl_sgix_fragment_lighting = e.find("GL_SGIX_fragment_lighting")!=e.end();
  gl_sgix_framezoom = e.find("GL_SGIX_framezoom")!=e.end();
  gl_sgix_igloo_interface = e.find("GL_SGIX_igloo_interface")!=e.end();
  gl_sgix_instruments = e.find("GL_SGIX_instruments")!=e.end();
  gl_sgix_list_priority = e.find("GL_SGIX_list_priority")!=e.end();
  gl_sgix_pixel_texture = e.find("GL_SGIX_pixel_texture")!=e.end();
  gl_sgix_polynomial_ffd = e.find("GL_SGIX_polynomial_ffd")!=e.end();
  gl_sgix_reference_plane = e.find("GL_SGIX_reference_plane")!=e.end();
  gl_sgix_sprite = e.find("GL_SGIX_sprite")!=e.end();
  gl_sgix_tag_sample_buffer = e.find("GL_SGIX_tag_sample_buffer")!=e.end();
  gl_sgi_color_table = e.find("GL_SGI_color_table")!=e.end();
  gl_sunx_constant_data = e.find("GL_SUNX_constant_data")!=e.end();
  gl_sun_global_alpha = e.find("GL_SUN_global_alpha")!=e.end();
  gl_sun_mesh_array = e.find("GL_SUN_mesh_array")!=e.end();
  gl_sun_read_video_pixels = e.find("GL_SUN_read_video_pixels")!=e.end();
  gl_sun_triangle_list = e.find("GL_SUN_triangle_list")!=e.end();
  gl_sun_vertex = e.find("GL_SUN_vertex")!=e.end();
  gl_win_swap_hint = e.find("GL_WIN_swap_hint")!=e.end();

#ifdef REGAL_SYS_WGL
  wgl_3dl_stereo_control = e.find("WGL_3DL_stereo_control")!=e.end();
  wgl_amd_gpu_association = e.find("WGL_AMD_gpu_association")!=e.end();
  wgl_arb_buffer_region = e.find("WGL_ARB_buffer_region")!=e.end();
  wgl_arb_create_context = e.find("WGL_ARB_create_context")!=e.end();
  wgl_arb_extensions_string = e.find("WGL_ARB_extensions_string")!=e.end();
  wgl_arb_make_current_read = e.find("WGL_ARB_make_current_read")!=e.end();
  wgl_arb_pbuffer = e.find("WGL_ARB_pbuffer")!=e.end();
  wgl_arb_pixel_format = e.find("WGL_ARB_pixel_format")!=e.end();
  wgl_arb_render_texture = e.find("WGL_ARB_render_texture")!=e.end();
  wgl_ext_display_color_table = e.find("WGL_EXT_display_color_table")!=e.end();
  wgl_ext_extensions_string = e.find("WGL_EXT_extensions_string")!=e.end();
  wgl_ext_make_current_read = e.find("WGL_EXT_make_current_read")!=e.end();
  wgl_ext_pbuffer = e.find("WGL_EXT_pbuffer")!=e.end();
  wgl_ext_pixel_format = e.find("WGL_EXT_pixel_format")!=e.end();
  wgl_ext_swap_control = e.find("WGL_EXT_swap_control")!=e.end();
  wgl_gdi = e.find("WGL_GDI")!=e.end();
  wgl_i3d_digital_video_control = e.find("WGL_I3D_digital_video_control")!=e.end();
  wgl_i3d_gamma = e.find("WGL_I3D_gamma")!=e.end();
  wgl_i3d_genlock = e.find("WGL_I3D_genlock")!=e.end();
  wgl_i3d_image_buffer = e.find("WGL_I3D_image_buffer")!=e.end();
  wgl_i3d_swap_frame_lock = e.find("WGL_I3D_swap_frame_lock")!=e.end();
  wgl_i3d_swap_frame_usage = e.find("WGL_I3D_swap_frame_usage")!=e.end();
  wgl_nv_copy_image = e.find("WGL_NV_copy_image")!=e.end();
  wgl_nv_gpu_affinity = e.find("WGL_NV_gpu_affinity")!=e.end();
  wgl_nv_present_video = e.find("WGL_NV_present_video")!=e.end();
  wgl_nv_swap_group = e.find("WGL_NV_swap_group")!=e.end();
  wgl_nv_vertex_array_range = e.find("WGL_NV_vertex_array_range")!=e.end();
  wgl_nv_video_capture = e.find("WGL_NV_video_capture")!=e.end();
  wgl_nv_video_output = e.find("WGL_NV_video_output")!=e.end();
  wgl_oml_sync_control = e.find("WGL_OML_sync_control")!=e.end();
#endif

#ifdef REGAL_SYS_GLX
  glx_arb_create_context = e.find("GLX_ARB_create_context")!=e.end();
  glx_arb_get_proc_address = e.find("GLX_ARB_get_proc_address")!=e.end();
  glx_ati_render_texture = e.find("GLX_ATI_render_texture")!=e.end();
  glx_ext_import_context = e.find("GLX_EXT_import_context")!=e.end();
  glx_ext_swap_control = e.find("GLX_EXT_swap_control")!=e.end();
  glx_ext_texture_from_pixmap = e.find("GLX_EXT_texture_from_pixmap")!=e.end();
  glx_mesa_agp_offset = e.find("GLX_MESA_agp_offset")!=e.end();
  glx_mesa_copy_sub_buffer = e.find("GLX_MESA_copy_sub_buffer")!=e.end();
  glx_mesa_pixmap_colormap = e.find("GLX_MESA_pixmap_colormap")!=e.end();
  glx_mesa_release_buffers = e.find("GLX_MESA_release_buffers")!=e.end();
  glx_mesa_set_3dfx_mode = e.find("GLX_MESA_set_3dfx_mode")!=e.end();
  glx_nv_copy_image = e.find("GLX_NV_copy_image")!=e.end();
  glx_nv_present_video = e.find("GLX_NV_present_video")!=e.end();
  glx_nv_swap_group = e.find("GLX_NV_swap_group")!=e.end();
  glx_nv_vertex_array_range = e.find("GLX_NV_vertex_array_range")!=e.end();
  glx_nv_video_output = e.find("GLX_NV_video_output")!=e.end();
  glx_oml_sync_control = e.find("GLX_OML_sync_control")!=e.end();
  glx_sgix_fbconfig = e.find("GLX_SGIX_fbconfig")!=e.end();
  glx_sgix_pbuffer = e.find("GLX_SGIX_pbuffer")!=e.end();
  glx_sgix_swap_barrier = e.find("GLX_SGIX_swap_barrier")!=e.end();
  glx_sgix_swap_group = e.find("GLX_SGIX_swap_group")!=e.end();
  glx_sgix_video_resize = e.find("GLX_SGIX_video_resize")!=e.end();
  glx_sgi_cushion = e.find("GLX_SGI_cushion")!=e.end();
  glx_sgi_make_current_read = e.find("GLX_SGI_make_current_read")!=e.end();
  glx_sgi_swap_control = e.find("GLX_SGI_swap_control")!=e.end();
  glx_sgi_video_sync = e.find("GLX_SGI_video_sync")!=e.end();
  glx_sun_get_transparent_index = e.find("GLX_SUN_get_transparent_index")!=e.end();
  glx_sun_video_resize = e.find("GLX_SUN_video_resize")!=e.end();
#endif

  RegalAssert(context.dsp->driverTbl.glGetIntegerv);
  context.dsp->driverTbl.glGetIntegerv( GL_MAX_VERTEX_ATTRIBS, reinterpret_cast<GLint *>(&maxVertexAttribs));

  if (maxVertexAttribs > REGAL_MAX_VERTEX_ATTRIBS)
      maxVertexAttribs = REGAL_MAX_VERTEX_ATTRIBS;

  // Qualcomm fails with float4 attribs with 256 byte stride, so artificially limit to 8 attribs
  if (vendor == "Qualcomm")
    maxVertexAttribs = 8;
}

bool
ContextInfo::getExtension(const char *ext) const
{
  ITrace("ContextInfo::getExtension ",boost::print::quote(ext,'"'));

  if (!strcmp(ext,"GL_3DFX_tbuffer")) return gl_3dfx_tbuffer;
  if (!strcmp(ext,"GL_AMD_debug_output")) return gl_amd_debug_output;
  if (!strcmp(ext,"GL_AMD_draw_buffers_blend")) return gl_amd_draw_buffers_blend;
  if (!strcmp(ext,"GL_AMD_multi_draw_indirect")) return gl_amd_multi_draw_indirect;
  if (!strcmp(ext,"GL_AMD_name_gen_delete")) return gl_amd_name_gen_delete;
  if (!strcmp(ext,"GL_AMD_performance_monitor")) return gl_amd_performance_monitor;
  if (!strcmp(ext,"GL_AMD_sample_positions")) return gl_amd_sample_positions;
  if (!strcmp(ext,"GL_AMD_stencil_operation_extended")) return gl_amd_stencil_operation_extended;
  if (!strcmp(ext,"GL_AMD_vertex_shader_tessellator")) return gl_amd_vertex_shader_tessellator;
  if (!strcmp(ext,"GL_APPLE_element_array")) return gl_apple_element_array;
  if (!strcmp(ext,"GL_APPLE_fence")) return gl_apple_fence;
  if (!strcmp(ext,"GL_APPLE_flush_buffer_range")) return gl_apple_flush_buffer_range;
  if (!strcmp(ext,"GL_APPLE_flush_render")) return gl_apple_flush_render;
  if (!strcmp(ext,"GL_APPLE_object_purgeable")) return gl_apple_object_purgeable;
  if (!strcmp(ext,"GL_APPLE_texture_range")) return gl_apple_texture_range;
  if (!strcmp(ext,"GL_APPLE_vertex_array_object")) return gl_apple_vertex_array_object;
  if (!strcmp(ext,"GL_APPLE_vertex_array_range")) return gl_apple_vertex_array_range;
  if (!strcmp(ext,"GL_APPLE_vertex_program_evaluators")) return gl_apple_vertex_program_evaluators;
  if (!strcmp(ext,"GL_ARB_ES2_compatibility")) return gl_arb_es2_compatibility;
  if (!strcmp(ext,"GL_ARB_base_instance")) return gl_arb_base_instance;
  if (!strcmp(ext,"GL_ARB_blend_func_extended")) return gl_arb_blend_func_extended;
  if (!strcmp(ext,"GL_ARB_cl_event")) return gl_arb_cl_event;
  if (!strcmp(ext,"GL_ARB_color_buffer_float")) return gl_arb_color_buffer_float;
  if (!strcmp(ext,"GL_ARB_copy_buffer")) return gl_arb_copy_buffer;
  if (!strcmp(ext,"GL_ARB_debug_output")) return gl_arb_debug_output;
  if (!strcmp(ext,"GL_ARB_draw_buffers")) return gl_arb_draw_buffers;
  if (!strcmp(ext,"GL_ARB_draw_buffers_blend")) return gl_arb_draw_buffers_blend;
  if (!strcmp(ext,"GL_ARB_draw_elements_base_vertex")) return gl_arb_draw_elements_base_vertex;
  if (!strcmp(ext,"GL_ARB_draw_indirect")) return gl_arb_draw_indirect;
  if (!strcmp(ext,"GL_ARB_draw_instanced")) return gl_arb_draw_instanced;
  if (!strcmp(ext,"GL_ARB_framebuffer_object")) return gl_arb_framebuffer_object;
  if (!strcmp(ext,"GL_ARB_geometry_shader4")) return gl_arb_geometry_shader4;
  if (!strcmp(ext,"GL_ARB_get_program_binary")) return gl_arb_get_program_binary;
  if (!strcmp(ext,"GL_ARB_gpu_shader_fp64")) return gl_arb_gpu_shader_fp64;
  if (!strcmp(ext,"GL_ARB_half_float_pixel")) return gl_arb_half_float_pixel;
  if (!strcmp(ext,"GL_ARB_imaging")) return gl_arb_imaging;
  if (!strcmp(ext,"GL_ARB_instanced_arrays")) return gl_arb_instanced_arrays;
  if (!strcmp(ext,"GL_ARB_internalformat_query")) return gl_arb_internalformat_query;
  if (!strcmp(ext,"GL_ARB_map_buffer_range")) return gl_arb_map_buffer_range;
  if (!strcmp(ext,"GL_ARB_matrix_palette")) return gl_arb_matrix_palette;
  if (!strcmp(ext,"GL_ARB_multisample")) return gl_arb_multisample;
  if (!strcmp(ext,"GL_ARB_multitexture")) return gl_arb_multitexture;
  if (!strcmp(ext,"GL_ARB_occlusion_query")) return gl_arb_occlusion_query;
  if (!strcmp(ext,"GL_ARB_point_parameters")) return gl_arb_point_parameters;
  if (!strcmp(ext,"GL_ARB_provoking_vertex")) return gl_arb_provoking_vertex;
  if (!strcmp(ext,"GL_ARB_robustness")) return gl_arb_robustness;
  if (!strcmp(ext,"GL_ARB_sample_shading")) return gl_arb_sample_shading;
  if (!strcmp(ext,"GL_ARB_sampler_objects")) return gl_arb_sampler_objects;
  if (!strcmp(ext,"GL_ARB_separate_shader_objects")) return gl_arb_separate_shader_objects;
  if (!strcmp(ext,"GL_ARB_shader_objects")) return gl_arb_shader_objects;
  if (!strcmp(ext,"GL_ARB_shader_subroutine")) return gl_arb_shader_subroutine;
  if (!strcmp(ext,"GL_ARB_shading_language_include")) return gl_arb_shading_language_include;
  if (!strcmp(ext,"GL_ARB_sync")) return gl_arb_sync;
  if (!strcmp(ext,"GL_ARB_tessellation_shader")) return gl_arb_tessellation_shader;
  if (!strcmp(ext,"GL_ARB_texture_buffer_object")) return gl_arb_texture_buffer_object;
  if (!strcmp(ext,"GL_ARB_texture_compression")) return gl_arb_texture_compression;
  if (!strcmp(ext,"GL_ARB_texture_multisample")) return gl_arb_texture_multisample;
  if (!strcmp(ext,"GL_ARB_texture_storage")) return gl_arb_texture_storage;
  if (!strcmp(ext,"GL_ARB_timer_query")) return gl_arb_timer_query;
  if (!strcmp(ext,"GL_ARB_transform_feedback2")) return gl_arb_transform_feedback2;
  if (!strcmp(ext,"GL_ARB_transform_feedback3")) return gl_arb_transform_feedback3;
  if (!strcmp(ext,"GL_ARB_transform_feedback_instanced")) return gl_arb_transform_feedback_instanced;
  if (!strcmp(ext,"GL_ARB_transpose_matrix")) return gl_arb_transpose_matrix;
  if (!strcmp(ext,"GL_ARB_uniform_buffer_object")) return gl_arb_uniform_buffer_object;
  if (!strcmp(ext,"GL_ARB_vertex_array_object")) return gl_arb_vertex_array_object;
  if (!strcmp(ext,"GL_ARB_vertex_attrib_64bit")) return gl_arb_vertex_attrib_64bit;
  if (!strcmp(ext,"GL_ARB_vertex_blend")) return gl_arb_vertex_blend;
  if (!strcmp(ext,"GL_ARB_vertex_buffer_object")) return gl_arb_vertex_buffer_object;
  if (!strcmp(ext,"GL_ARB_vertex_program")) return gl_arb_vertex_program;
  if (!strcmp(ext,"GL_ARB_vertex_shader")) return gl_arb_vertex_shader;
  if (!strcmp(ext,"GL_ARB_vertex_type_2_10_10_10_rev")) return gl_arb_vertex_type_2_10_10_10_rev;
  if (!strcmp(ext,"GL_ARB_viewport_array")) return gl_arb_viewport_array;
  if (!strcmp(ext,"GL_ARB_window_pos")) return gl_arb_window_pos;
  if (!strcmp(ext,"GL_ATI_draw_buffers")) return gl_ati_draw_buffers;
  if (!strcmp(ext,"GL_ATI_element_array")) return gl_ati_element_array;
  if (!strcmp(ext,"GL_ATI_envmap_bumpmap")) return gl_ati_envmap_bumpmap;
  if (!strcmp(ext,"GL_ATI_fragment_shader")) return gl_ati_fragment_shader;
  if (!strcmp(ext,"GL_ATI_map_object_buffer")) return gl_ati_map_object_buffer;
  if (!strcmp(ext,"GL_ATI_pn_triangles")) return gl_ati_pn_triangles;
  if (!strcmp(ext,"GL_ATI_separate_stencil")) return gl_ati_separate_stencil;
  if (!strcmp(ext,"GL_ATI_vertex_array_object")) return gl_ati_vertex_array_object;
  if (!strcmp(ext,"GL_ATI_vertex_attrib_array_object")) return gl_ati_vertex_attrib_array_object;
  if (!strcmp(ext,"GL_ATI_vertex_streams")) return gl_ati_vertex_streams;
  if (!strcmp(ext,"GL_EXT_bindable_uniform")) return gl_ext_bindable_uniform;
  if (!strcmp(ext,"GL_EXT_blend_color")) return gl_ext_blend_color;
  if (!strcmp(ext,"GL_EXT_blend_equation_separate")) return gl_ext_blend_equation_separate;
  if (!strcmp(ext,"GL_EXT_blend_func_separate")) return gl_ext_blend_func_separate;
  if (!strcmp(ext,"GL_EXT_blend_minmax")) return gl_ext_blend_minmax;
  if (!strcmp(ext,"GL_EXT_color_subtable")) return gl_ext_color_subtable;
  if (!strcmp(ext,"GL_EXT_compiled_vertex_array")) return gl_ext_compiled_vertex_array;
  if (!strcmp(ext,"GL_EXT_convolution")) return gl_ext_convolution;
  if (!strcmp(ext,"GL_EXT_coordinate_frame")) return gl_ext_coordinate_frame;
  if (!strcmp(ext,"GL_EXT_copy_texture")) return gl_ext_copy_texture;
  if (!strcmp(ext,"GL_EXT_cull_vertex")) return gl_ext_cull_vertex;
  if (!strcmp(ext,"GL_EXT_debug_marker")) return gl_ext_debug_marker;
  if (!strcmp(ext,"GL_EXT_depth_bounds_test")) return gl_ext_depth_bounds_test;
  if (!strcmp(ext,"GL_EXT_direct_state_access")) return gl_ext_direct_state_access;
  if (!strcmp(ext,"GL_EXT_draw_buffers2")) return gl_ext_draw_buffers2;
  if (!strcmp(ext,"GL_EXT_draw_instanced")) return gl_ext_draw_instanced;
  if (!strcmp(ext,"GL_EXT_draw_range_elements")) return gl_ext_draw_range_elements;
  if (!strcmp(ext,"GL_EXT_fog_coord")) return gl_ext_fog_coord;
  if (!strcmp(ext,"GL_EXT_fragment_lighting")) return gl_ext_fragment_lighting;
  if (!strcmp(ext,"GL_EXT_framebuffer_blit")) return gl_ext_framebuffer_blit;
  if (!strcmp(ext,"GL_EXT_framebuffer_multisample")) return gl_ext_framebuffer_multisample;
  if (!strcmp(ext,"GL_EXT_framebuffer_object")) return gl_ext_framebuffer_object;
  if (!strcmp(ext,"GL_EXT_geometry_shader4")) return gl_ext_geometry_shader4;
  if (!strcmp(ext,"GL_EXT_gpu_program_parameters")) return gl_ext_gpu_program_parameters;
  if (!strcmp(ext,"GL_EXT_gpu_shader4")) return gl_ext_gpu_shader4;
  if (!strcmp(ext,"GL_EXT_histogram")) return gl_ext_histogram;
  if (!strcmp(ext,"GL_EXT_index_func")) return gl_ext_index_func;
  if (!strcmp(ext,"GL_EXT_index_material")) return gl_ext_index_material;
  if (!strcmp(ext,"GL_EXT_light_texture")) return gl_ext_light_texture;
  if (!strcmp(ext,"GL_EXT_multi_draw_arrays")) return gl_ext_multi_draw_arrays;
  if (!strcmp(ext,"GL_EXT_multisample")) return gl_ext_multisample;
  if (!strcmp(ext,"GL_EXT_paletted_texture")) return gl_ext_paletted_texture;
  if (!strcmp(ext,"GL_EXT_pixel_transform")) return gl_ext_pixel_transform;
  if (!strcmp(ext,"GL_EXT_point_parameters")) return gl_ext_point_parameters;
  if (!strcmp(ext,"GL_EXT_polygon_offset")) return gl_ext_polygon_offset;
  if (!strcmp(ext,"GL_EXT_provoking_vertex")) return gl_ext_provoking_vertex;
  if (!strcmp(ext,"GL_EXT_scene_marker")) return gl_ext_scene_marker;
  if (!strcmp(ext,"GL_EXT_secondary_color")) return gl_ext_secondary_color;
  if (!strcmp(ext,"GL_EXT_separate_shader_objects")) return gl_ext_separate_shader_objects;
  if (!strcmp(ext,"GL_EXT_shader_image_load_store")) return gl_ext_shader_image_load_store;
  if (!strcmp(ext,"GL_EXT_stencil_clear_tag")) return gl_ext_stencil_clear_tag;
  if (!strcmp(ext,"GL_EXT_stencil_two_side")) return gl_ext_stencil_two_side;
  if (!strcmp(ext,"GL_EXT_subtexture")) return gl_ext_subtexture;
  if (!strcmp(ext,"GL_EXT_texture3D")) return gl_ext_texture3d;
  if (!strcmp(ext,"GL_EXT_texture_array")) return gl_ext_texture_array;
  if (!strcmp(ext,"GL_EXT_texture_buffer_object")) return gl_ext_texture_buffer_object;
  if (!strcmp(ext,"GL_EXT_texture_integer")) return gl_ext_texture_integer;
  if (!strcmp(ext,"GL_EXT_texture_object")) return gl_ext_texture_object;
  if (!strcmp(ext,"GL_EXT_texture_perturb_normal")) return gl_ext_texture_perturb_normal;
  if (!strcmp(ext,"GL_EXT_timer_query")) return gl_ext_timer_query;
  if (!strcmp(ext,"GL_EXT_transform_feedback")) return gl_ext_transform_feedback;
  if (!strcmp(ext,"GL_EXT_vertex_array")) return gl_ext_vertex_array;
  if (!strcmp(ext,"GL_EXT_vertex_attrib_64bit")) return gl_ext_vertex_attrib_64bit;
  if (!strcmp(ext,"GL_EXT_vertex_shader")) return gl_ext_vertex_shader;
  if (!strcmp(ext,"GL_EXT_vertex_weighting")) return gl_ext_vertex_weighting;
  if (!strcmp(ext,"GL_EXT_x11_sync_object")) return gl_ext_x11_sync_object;
  if (!strcmp(ext,"GL_GREMEDY_frame_terminator")) return gl_gremedy_frame_terminator;
  if (!strcmp(ext,"GL_GREMEDY_string_marker")) return gl_gremedy_string_marker;
  if (!strcmp(ext,"GL_HP_image_transform")) return gl_hp_image_transform;
  if (!strcmp(ext,"GL_IBM_multimode_draw_arrays")) return gl_ibm_multimode_draw_arrays;
  if (!strcmp(ext,"GL_IBM_vertex_array_lists")) return gl_ibm_vertex_array_lists;
  if (!strcmp(ext,"GL_INGR_blend_func_separate")) return gl_ingr_blend_func_separate;
  if (!strcmp(ext,"GL_INTEL_parallel_arrays")) return gl_intel_parallel_arrays;
  if (!strcmp(ext,"GL_INTEL_texture_scissor")) return gl_intel_texture_scissor;
  if (!strcmp(ext,"GL_KTX_buffer_region")) return gl_ktx_buffer_region;
  if (!strcmp(ext,"GL_MESA_resize_buffers")) return gl_mesa_resize_buffers;
  if (!strcmp(ext,"GL_MESA_window_pos")) return gl_mesa_window_pos;
  if (!strcmp(ext,"GL_NV_bindless_texture")) return gl_nv_bindless_texture;
  if (!strcmp(ext,"GL_NV_conditional_render")) return gl_nv_conditional_render;
  if (!strcmp(ext,"GL_NV_copy_image")) return gl_nv_copy_image;
  if (!strcmp(ext,"GL_NV_depth_buffer_float")) return gl_nv_depth_buffer_float;
  if (!strcmp(ext,"GL_NV_evaluators")) return gl_nv_evaluators;
  if (!strcmp(ext,"GL_NV_explicit_multisample")) return gl_nv_explicit_multisample;
  if (!strcmp(ext,"GL_NV_fence")) return gl_nv_fence;
  if (!strcmp(ext,"GL_NV_fragment_program")) return gl_nv_fragment_program;
  if (!strcmp(ext,"GL_NV_framebuffer_multisample_coverage")) return gl_nv_framebuffer_multisample_coverage;
  if (!strcmp(ext,"GL_NV_geometry_program4")) return gl_nv_geometry_program4;
  if (!strcmp(ext,"GL_NV_gpu_program4")) return gl_nv_gpu_program4;
  if (!strcmp(ext,"GL_NV_gpu_shader5")) return gl_nv_gpu_shader5;
  if (!strcmp(ext,"GL_NV_half_float")) return gl_nv_half_float;
  if (!strcmp(ext,"GL_NV_occlusion_query")) return gl_nv_occlusion_query;
  if (!strcmp(ext,"GL_NV_parameter_buffer_object")) return gl_nv_parameter_buffer_object;
  if (!strcmp(ext,"GL_NV_path_rendering")) return gl_nv_path_rendering;
  if (!strcmp(ext,"GL_NV_pixel_data_range")) return gl_nv_pixel_data_range;
  if (!strcmp(ext,"GL_NV_point_sprite")) return gl_nv_point_sprite;
  if (!strcmp(ext,"GL_NV_present_video")) return gl_nv_present_video;
  if (!strcmp(ext,"GL_NV_primitive_restart")) return gl_nv_primitive_restart;
  if (!strcmp(ext,"GL_NV_register_combiners")) return gl_nv_register_combiners;
  if (!strcmp(ext,"GL_NV_register_combiners2")) return gl_nv_register_combiners2;
  if (!strcmp(ext,"GL_NV_shader_buffer_load")) return gl_nv_shader_buffer_load;
  if (!strcmp(ext,"GL_NV_texture_barrier")) return gl_nv_texture_barrier;
  if (!strcmp(ext,"GL_NV_texture_multisample")) return gl_nv_texture_multisample;
  if (!strcmp(ext,"GL_NV_transform_feedback")) return gl_nv_transform_feedback;
  if (!strcmp(ext,"GL_NV_transform_feedback2")) return gl_nv_transform_feedback2;
  if (!strcmp(ext,"GL_NV_vdpau_interop")) return gl_nv_vdpau_interop;
  if (!strcmp(ext,"GL_NV_vertex_array_range")) return gl_nv_vertex_array_range;
  if (!strcmp(ext,"GL_NV_vertex_attrib_integer_64bit")) return gl_nv_vertex_attrib_integer_64bit;
  if (!strcmp(ext,"GL_NV_vertex_buffer_unified_memory")) return gl_nv_vertex_buffer_unified_memory;
  if (!strcmp(ext,"GL_NV_vertex_program")) return gl_nv_vertex_program;
  if (!strcmp(ext,"GL_NV_vertex_program4")) return gl_nv_vertex_program4;
  if (!strcmp(ext,"GL_NV_video_capture")) return gl_nv_video_capture;
  if (!strcmp(ext,"GL_PGI_misc_hints")) return gl_pgi_misc_hints;
  if (!strcmp(ext,"GL_REGAL_error_string")) return true;
  if (!strcmp(ext,"GL_REGAL_extension_query")) return true;
  if (!strcmp(ext,"GL_SGIS_detail_texture")) return gl_sgis_detail_texture;
  if (!strcmp(ext,"GL_SGIS_fog_function")) return gl_sgis_fog_function;
  if (!strcmp(ext,"GL_SGIS_multisample")) return gl_sgis_multisample;
  if (!strcmp(ext,"GL_SGIS_pixel_texture")) return gl_sgis_pixel_texture;
  if (!strcmp(ext,"GL_SGIS_point_parameters")) return gl_sgis_point_parameters;
  if (!strcmp(ext,"GL_SGIS_sharpen_texture")) return gl_sgis_sharpen_texture;
  if (!strcmp(ext,"GL_SGIS_texture4D")) return gl_sgis_texture4d;
  if (!strcmp(ext,"GL_SGIS_texture_color_mask")) return gl_sgis_texture_color_mask;
  if (!strcmp(ext,"GL_SGIS_texture_filter4")) return gl_sgis_texture_filter4;
  if (!strcmp(ext,"GL_SGIX_async")) return gl_sgix_async;
  if (!strcmp(ext,"GL_SGIX_flush_raster")) return gl_sgix_flush_raster;
  if (!strcmp(ext,"GL_SGIX_fog_texture")) return gl_sgix_fog_texture;
  if (!strcmp(ext,"GL_SGIX_fragment_lighting")) return gl_sgix_fragment_lighting;
  if (!strcmp(ext,"GL_SGIX_framezoom")) return gl_sgix_framezoom;
  if (!strcmp(ext,"GL_SGIX_igloo_interface")) return gl_sgix_igloo_interface;
  if (!strcmp(ext,"GL_SGIX_instruments")) return gl_sgix_instruments;
  if (!strcmp(ext,"GL_SGIX_list_priority")) return gl_sgix_list_priority;
  if (!strcmp(ext,"GL_SGIX_pixel_texture")) return gl_sgix_pixel_texture;
  if (!strcmp(ext,"GL_SGIX_polynomial_ffd")) return gl_sgix_polynomial_ffd;
  if (!strcmp(ext,"GL_SGIX_reference_plane")) return gl_sgix_reference_plane;
  if (!strcmp(ext,"GL_SGIX_sprite")) return gl_sgix_sprite;
  if (!strcmp(ext,"GL_SGIX_tag_sample_buffer")) return gl_sgix_tag_sample_buffer;
  if (!strcmp(ext,"GL_SGI_color_table")) return gl_sgi_color_table;
  if (!strcmp(ext,"GL_SUNX_constant_data")) return gl_sunx_constant_data;
  if (!strcmp(ext,"GL_SUN_global_alpha")) return gl_sun_global_alpha;
  if (!strcmp(ext,"GL_SUN_mesh_array")) return gl_sun_mesh_array;
  if (!strcmp(ext,"GL_SUN_read_video_pixels")) return gl_sun_read_video_pixels;
  if (!strcmp(ext,"GL_SUN_triangle_list")) return gl_sun_triangle_list;
  if (!strcmp(ext,"GL_SUN_vertex")) return gl_sun_vertex;
  if (!strcmp(ext,"GL_WIN_swap_hint")) return gl_win_swap_hint;

#ifdef REGAL_SYS_WGL
  if (!strcmp(ext,"WGL_3DL_stereo_control")) return wgl_3dl_stereo_control;
  if (!strcmp(ext,"WGL_AMD_gpu_association")) return wgl_amd_gpu_association;
  if (!strcmp(ext,"WGL_ARB_buffer_region")) return wgl_arb_buffer_region;
  if (!strcmp(ext,"WGL_ARB_create_context")) return wgl_arb_create_context;
  if (!strcmp(ext,"WGL_ARB_extensions_string")) return wgl_arb_extensions_string;
  if (!strcmp(ext,"WGL_ARB_make_current_read")) return wgl_arb_make_current_read;
  if (!strcmp(ext,"WGL_ARB_pbuffer")) return wgl_arb_pbuffer;
  if (!strcmp(ext,"WGL_ARB_pixel_format")) return wgl_arb_pixel_format;
  if (!strcmp(ext,"WGL_ARB_render_texture")) return wgl_arb_render_texture;
  if (!strcmp(ext,"WGL_EXT_display_color_table")) return wgl_ext_display_color_table;
  if (!strcmp(ext,"WGL_EXT_extensions_string")) return wgl_ext_extensions_string;
  if (!strcmp(ext,"WGL_EXT_make_current_read")) return wgl_ext_make_current_read;
  if (!strcmp(ext,"WGL_EXT_pbuffer")) return wgl_ext_pbuffer;
  if (!strcmp(ext,"WGL_EXT_pixel_format")) return wgl_ext_pixel_format;
  if (!strcmp(ext,"WGL_EXT_swap_control")) return wgl_ext_swap_control;
  if (!strcmp(ext,"WGL_GDI")) return wgl_gdi;
  if (!strcmp(ext,"WGL_I3D_digital_video_control")) return wgl_i3d_digital_video_control;
  if (!strcmp(ext,"WGL_I3D_gamma")) return wgl_i3d_gamma;
  if (!strcmp(ext,"WGL_I3D_genlock")) return wgl_i3d_genlock;
  if (!strcmp(ext,"WGL_I3D_image_buffer")) return wgl_i3d_image_buffer;
  if (!strcmp(ext,"WGL_I3D_swap_frame_lock")) return wgl_i3d_swap_frame_lock;
  if (!strcmp(ext,"WGL_I3D_swap_frame_usage")) return wgl_i3d_swap_frame_usage;
  if (!strcmp(ext,"WGL_NV_copy_image")) return wgl_nv_copy_image;
  if (!strcmp(ext,"WGL_NV_gpu_affinity")) return wgl_nv_gpu_affinity;
  if (!strcmp(ext,"WGL_NV_present_video")) return wgl_nv_present_video;
  if (!strcmp(ext,"WGL_NV_swap_group")) return wgl_nv_swap_group;
  if (!strcmp(ext,"WGL_NV_vertex_array_range")) return wgl_nv_vertex_array_range;
  if (!strcmp(ext,"WGL_NV_video_capture")) return wgl_nv_video_capture;
  if (!strcmp(ext,"WGL_NV_video_output")) return wgl_nv_video_output;
  if (!strcmp(ext,"WGL_OML_sync_control")) return wgl_oml_sync_control;
#endif

#ifdef REGAL_SYS_GLX
  if (!strcmp(ext,"GLX_ARB_create_context")) return glx_arb_create_context;
  if (!strcmp(ext,"GLX_ARB_get_proc_address")) return glx_arb_get_proc_address;
  if (!strcmp(ext,"GLX_ATI_render_texture")) return glx_ati_render_texture;
  if (!strcmp(ext,"GLX_EXT_import_context")) return glx_ext_import_context;
  if (!strcmp(ext,"GLX_EXT_swap_control")) return glx_ext_swap_control;
  if (!strcmp(ext,"GLX_EXT_texture_from_pixmap")) return glx_ext_texture_from_pixmap;
  if (!strcmp(ext,"GLX_MESA_agp_offset")) return glx_mesa_agp_offset;
  if (!strcmp(ext,"GLX_MESA_copy_sub_buffer")) return glx_mesa_copy_sub_buffer;
  if (!strcmp(ext,"GLX_MESA_pixmap_colormap")) return glx_mesa_pixmap_colormap;
  if (!strcmp(ext,"GLX_MESA_release_buffers")) return glx_mesa_release_buffers;
  if (!strcmp(ext,"GLX_MESA_set_3dfx_mode")) return glx_mesa_set_3dfx_mode;
  if (!strcmp(ext,"GLX_NV_copy_image")) return glx_nv_copy_image;
  if (!strcmp(ext,"GLX_NV_present_video")) return glx_nv_present_video;
  if (!strcmp(ext,"GLX_NV_swap_group")) return glx_nv_swap_group;
  if (!strcmp(ext,"GLX_NV_vertex_array_range")) return glx_nv_vertex_array_range;
  if (!strcmp(ext,"GLX_NV_video_output")) return glx_nv_video_output;
  if (!strcmp(ext,"GLX_OML_sync_control")) return glx_oml_sync_control;
  if (!strcmp(ext,"GLX_SGIX_fbconfig")) return glx_sgix_fbconfig;
  if (!strcmp(ext,"GLX_SGIX_pbuffer")) return glx_sgix_pbuffer;
  if (!strcmp(ext,"GLX_SGIX_swap_barrier")) return glx_sgix_swap_barrier;
  if (!strcmp(ext,"GLX_SGIX_swap_group")) return glx_sgix_swap_group;
  if (!strcmp(ext,"GLX_SGIX_video_resize")) return glx_sgix_video_resize;
  if (!strcmp(ext,"GLX_SGI_cushion")) return glx_sgi_cushion;
  if (!strcmp(ext,"GLX_SGI_make_current_read")) return glx_sgi_make_current_read;
  if (!strcmp(ext,"GLX_SGI_swap_control")) return glx_sgi_swap_control;
  if (!strcmp(ext,"GLX_SGI_video_sync")) return glx_sgi_video_sync;
  if (!strcmp(ext,"GLX_SUN_get_transparent_index")) return glx_sun_get_transparent_index;
  if (!strcmp(ext,"GLX_SUN_video_resize")) return glx_sun_video_resize;
#endif

return false;
}

bool
ContextInfo::isSupported(const char *ext) const
{
  ITrace("ContextInfo::isSupported ",boost::print::quote(ext,'"'));

  string_list<string> e;
  e.split(ext,' ');
  for (string_list<string>::const_iterator i=e.begin(); i!=e.end(); ++i)
    if (i->length() && !getExtension(i->c_str())) return false;
  return true;
}

REGAL_NAMESPACE_END
